server.port=8081

spring.datasource.url=jdbc:mysql://root:gfcpLzXeEpvkUZOIHhGDeORbMlyEwYVt@switchyard.proxy.rlwy.net:25811/railway
spring.datasource.username=$root
spring.datasource.password=gfcpLzXeEpvkUZOIHhGDeORbMlyEwYVt

spring.jpa.hibernate.ddl-auto=update

jwt.secret=RkFrZVNlY3JldEZvckhTMjU2XzMyQnl0ZXNfISEhISEhISE=
jwt.expiration=86400000

spring.main.allow-bean-definition-overriding=true
