server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: complaint-service
          uri: lb://COMPLAINT-SERVICE
          predicates:
            - Path=/complaints/**,/admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}



